server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/GAME_PROJECT?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456a
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.gameproject.gamebackend.entity